// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaoPnpATmZN3igYxvhu3cJ3BwAYC-2jVM',
    appId: '1:708215483312:web:e6513cace89ac2d98f4475',
    messagingSenderId: '708215483312',
    projectId: 'lumen-urban-escape',
    authDomain: 'lumen-urban-escape.firebaseapp.com',
    storageBucket: 'lumen-urban-escape.appspot.com',
    measurementId: 'G-831ZTWR3YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDckqOLQSEJlKHos2XgebvISOkfzZINlNs',
    appId: '1:708215483312:android:e54aaff544d470b78f4475',
    messagingSenderId: '708215483312',
    projectId: 'lumen-urban-escape',
    storageBucket: 'lumen-urban-escape.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGM-VBzECmnkq-_d5ArLdH9y3YTqwOFwQ',
    appId: '1:708215483312:ios:f8d303cc7d3804608f4475',
    messagingSenderId: '708215483312',
    projectId: 'lumen-urban-escape',
    storageBucket: 'lumen-urban-escape.appspot.com',
    iosClientId: '708215483312-rsplcvotdvcu1656ssq10gkov9uoa3m0.apps.googleusercontent.com',
    iosBundleId: 'com.example.urbanEscape',
  );
}
